### ISSUE TITLE
[TASK] Audit and Improve Webbsite

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-experiences#111]
### Tasks:

- [ ] Improve the look and feel of webbsite to enhance its sense of legitimacy & professionalism 
- [ ] Improve interactive states of various components
- [ ] Improve the use of colours of various components & BG images
- [ ] Improve images displayed on website 
- [ ] Test out & improve the navigation experience between Webbsite & Webb dApps 
- [ ] Improve copywriting & texts display sizes/margins
- [ ] Solicit feedback from team
