### ISSUE TITLE
[CHECKLIST] Make improvements to Webbsite

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-experiences#112]
### Tasks & Goals

- [x] https://github.com/webb-tools/webb-experiences/issues/118
- [ ] Touch-ups to improve interactive states
- [x] Improve Blog Cards (add dates)
- [x] https://github.com/webb-tools/webb-dapp/issues/1052
- [x] https://github.com/webb-tools/webb-dapp/issues/1242
- [x] https://github.com/webb-tools/webb-experiences/issues/156
- [ ] Improve Merkle Tree image size on webbsite
- [x] https://github.com/webb-tools/webb-experiences/issues/143
- [x] https://github.com/webb-tools/webb-experiences/issues/165
- [x] https://github.com/webb-tools/webb-experiences/issues/166

**Comment by monaiuu** [comment]
All of above will be addressed via this task:
https://github.com/webb-tools/webb-experiences/issues/197
