### ISSUE TITLE
[CHECKLIST] Explore account / note management dedicated page

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-experiences#130]
## Overview

With the dApp components growing we want to explore moving the account components away from main bridge flow and into a dedicated page. This would be accessible via the sidebar.

**Comment by monaiuu** [comment]
## Checklist

- [ ] https://github.com/webb-tools/webb-experiences/issues/126
- [ ] https://github.com/webb-tools/webb-experiences/issues/127
- [x] https://github.com/webb-tools/webb-experiences/issues/181
- [ ] https://github.com/webb-tools/webb-experiences/issues/175
- [x] https://github.com/webb-tools/webb-experiences/issues/187
