### ISSUE TITLE
[TASK] Improve Fees Display on Bridge dAPP

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-experiences#149]
## Tasks

We need to display better and inform users how fees work & calculated in deposit, transfer, and withdrawal for various contexts. See below for reference:

- [ ] Fees on Deposit
- [ ] Fees on Transfer w/o relayer
- [ ] Fees on Transfer with relayer
- [ ] Fees on Withdrawal w/o relayer
- [ ] Fees on Withdrawal with relayer
- [ ] Fees on Withdrawal with relayer + refund

@dutterbutter feel free to comment below to provide any useful context.

**Comment by dutterbutter** [comment]
- With relayer, fees will be paid in bridged / shielded token. 
- With relayer and refund, users will send additional bridged / shielded token in order to receive the native asset of the destination chain 
- Without relayer, users pay in native asset

**Comment by monaiuu** [comment]
Withdrawal on tornado reference:

![Image](https://github.com/webb-tools/webb-experiences/assets/109539270/968e0f07-2c40-4bfe-8316-2deec4246852)
