### ISSUE TITLE
[CHECKLIST] V2 Bridge Card Components

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-experiences#159]
## Description:
The existing bridge card components in Hubble Bridge need to be upgraded to V2 to enhance the user experience and accommodate new features and functionality.

### Goals:

- Improve the visual design and layout of the bridge card for a more intuitive and user-friendly experience.
- Accommodate additional networks and chains in the bridge card in transfer/withdrawal, allowing users to transfer and withdraw from multiple networks at once.
- Enhance the usability of the bridge card by optimizing the information hierarchy and providing more context on fees, refund features etc.
- Address any existing usability issues and pain points reported by users through user testing and feedback.

### Tasks:

- [x] https://github.com/webb-tools/webb-experiences/issues/178
- [x] https://github.com/webb-tools/webb-experiences/issues/134
- [x] https://github.com/webb-tools/webb-experiences/issues/122
- [x] https://github.com/webb-tools/webb-experiences/issues/157
- [ ] https://github.com/webb-tools/webb-experiences/issues/147
- [ ] https://github.com/webb-tools/webb-experiences/issues/141
- [x] https://github.com/webb-tools/webb-experiences/issues/146
- [ ] https://github.com/webb-tools/webb-experiences/issues/150
- [x] https://github.com/webb-tools/webb-dapp/issues/1080
- [x] https://github.com/webb-tools/webb-experiences/issues/153
- [x] https://github.com/webb-tools/webb-experiences/issues/149
- [x] https://github.com/webb-tools/webb-experiences/issues/180
