### ISSUE TITLE
[TASK] Address checklist tasks and create issues

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-experiences#208]
- [ ]  Lots of deadspace in first column of the Hubble Stats UI for token names
- [ ]  TWL table comments
    - [ ]  [BUG] Redundant WETH display in TWL table
    - [ ]  100% (percentage of total wrapping) is very small
    - [ ]  The token name for each row is all webbWETH when it should specify the exact asset of the row.
- [ ]  Change background colors of row headers (require table component upload in UI Kit)
    - [ ]  lighter for dark theme
    - [ ]  darker for light theme
- [ ]  Hubble bridge background image requires update to be consistent with Hubble Stats & DKG stats https://github.com/webb-tools/webb-dapp/issues/1591
- [ ]  ~~webbWETH row could be a dropdown?~~
- [ ]  Adding a custom relayer, if writing a custom URL (detect it using http or ://) to change the button to a button that reads `Add`. (make adding action more visible)
- [ ]  Wrapped token identification needs to be updated (webbETH, webbTNT etc.)
- [ ]  User rejected state → `Transaction Failed` has a blue tag. It should be red.
- [ ]  Tangle chain icon and chip icon need to be standardized (light purple vs. dark purple background)
- [ ]  When Hubble Statistics refreshes; the side nav state should remain consistent (currently it re-expands)
- [ ]  Hubble stats data needs to be refreshing in the background
    - [ ]  This needs to be a pattern we cement in our brains!!
- [ ]  [BUG] Hubble bridge wrap and deposit can be called repeatedly with the same spend note. (If it is not called correctly, it should not appear in the transaction progressor component)
- [ ]  Dismiss all notifications in transaction progressor component
