### ISSUE TITLE
Documentation and Usage

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-experiences#30]
## Overview 

As we look towards production, we will be updating our docs site to reflect the latest deployment details, protocol documentation, and dApp usage guides. 

### Deliverables 

- [ ] Update docs site
- [ ] Create usage documentation 
- [ ] Update deployment documentation 
- [ ] Add updated diagrams
