### ISSUE TITLE
Account Component

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-experiences#44]
## Product Design Goals

- Provide a intuitive and straightforward account creation flow
- Our goal is to allow users to easily view and manage account details
- Users should be able to effortlessly manage their secret notes

## Deliverables

- Create wireframes that represent and organize the user actions for interacting / creating an account via MetaMask
- Design a dedicated account component that displays key account details and provides easy note management access
- Create high fidelity prototype of a component dashboard and flow

## Designs and Product Flow

![Image](https://user-images.githubusercontent.com/29983536/191096045-7a6ea0b9-122c-4b68-83c4-55ff22b5ddef.png)

**Figure 1.0** - *Full account creation and register UI flow*

The above flow outlines the full account creation and register flow that is currently implemented. The below diagram illustrates just the account creation flow. 

![Image](https://user-images.githubusercontent.com/29983536/191096059-bc980278-83f4-46f2-b9f5-62cd98afd924.png)

**Figure 1.1 -** *Account Creation and login UI flow.*

## Feature Details

Users will be required to create a NoteAccount and register prior to depositing into the dApp. The NoteAccount Dashboard as an early iteration will display the following details about an account. Additional iterations we can consider including users total deposits or rewards in the bridge as well but for now we will include the following details:

- Display note account key
- Display note account balance
    - Total balance across all Notes
    - Balance per destination chain
- Load and decrypt all of your private notes with NoteAccount key
- Sync notes
    - Syncs notes to update
- Remove account info from current browser session
- Download raw private notes
- Quick transfer / withdraw buttons

## Second Feature Iterations

- Displays a list of their own transactions
    - deposits
    - withdraws

### An example of this can be seen on Tornado Nova:

<img src="https://user-images.githubusercontent.com/29983536/191096085-33c0f392-3521-4503-a934-c19b484705af.png" height=550 />

## Notifications

Notifications that should be present should include, but not limited to, 

- Note account created successfully
- Error creating note account
- Note successfully added
- Note successfully removed
- Note successfully downloaded
- Account successfully registered
- Error registering account

## Components List

- Account component
    - Account balances
 
### Relevant Links

- [Account component spec](https://www.notion.so/hicommonwealth/Feature-7-Account-Dashboard-cf906e09be8d488e8d9f3de2904a84a5)

# Open Questions

**Comment by monaiuu** [comment]
**Design Review 1 for Account Component** 

Documentations:

[FigJam File](https://www.figma.com/file/t3snazz1xsbTxYazoWy8Zu/Account-Review-%231?node-id=3%3A8545)

[Otter.ai](https://otter.ai/u/-SXujuyrCo6lli5aZ5PsvAIR3us)

**Comment by monaiuu** [comment]
**Design Review 2 for Account Component**

Documentations:

[Figma Prototype
](https://www.figma.com/proto/VHrPTN7saAlW1M64BjdjxQ/%F0%9F%91%A4-Account?page-id=193%3A49367&node-id=193%3A49368&viewport=240%2C834%2C0.27&scaling=scale-down&starting-point-node-id=193%3A49368)
[Otter.ai](https://otter.ai/u/5hybtGXBhGVRcO-r3wZbnAYeeZA)

**Comment by monaiuu** [comment]
### Goal: Final Bridge UI + Account Review and Hand-off on Tuesday (Oct 11th) 

**To-do list:**

- [x] Add note account features in all Bridge UI handoff wireframes (light + dark mode)
- [ ] Ensure all scenarios of how note account features interact with bridge UI are considered(deposit/transfer/withdraw)
- [x] Ensure all notifications are addressed
- [x] Add note account components in the design system

**Comment by monaiuu** [comment]
**Please see below for hand-off wireframes + prototype + design system components for Account Component.** 

👉 Some interactions possible between notes & bridge UI are addressed within (quick transaction feature). However, please note this hand-off is largely separated from the Bridge UI (deposit, withdraw, transfer), with focus on features related to Account Component only.

[**Hand-off Wireframe File**](https://www.figma.com/proto/VHrPTN7saAlW1M64BjdjxQ/%F0%9F%91%A4-Account?page-id=294%3A68233&node-id=316%3A108543&viewport=733%2C1892%2C0.07&scaling=scale-down&starting-point-node-id=316%3A108543)

[**Figma Prototype**](https://www.figma.com/proto/VHrPTN7saAlW1M64BjdjxQ/%F0%9F%91%A4-Account?page-id=294%3A68233&node-id=316%3A108543&viewport=733%2C1892%2C0.07&scaling=scale-down&starting-point-node-id=316%3A108543)

[**Updated Design System**](https://www.figma.com/file/H43lYnTCOAPjO9kTrrepe1/%F0%9F%95%B8%EF%B8%8F-Design-System?node-id=66%3A3687)

👉 Components related to **Account Component** are annotated with ⚪ in the updated [Design System](https://www.figma.com/file/H43lYnTCOAPjO9kTrrepe1/%F0%9F%95%B8%EF%B8%8F-Design-System?node-id=66%3A3687). 

![Image](https://user-images.githubusercontent.com/109539270/195224563-a39fe2d5-1940-4778-9a34-f2cfd769ba1c.png)



Let me know if there are any questions! 

@dutterbutter @seeddisperser
