### ISSUE TITLE
[PROCESS] Define Product Discovery, User Testing, and Experience methodology

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-experiences#53]
## Task Checklist

- [x] https://github.com/webb-tools/webb-experiences/issues/87
- [x] https://github.com/webb-tools/webb-experiences/issues/89
- [x] https://github.com/webb-tools/webb-experiences/issues/81
- [x] https://github.com/webb-tools/webb-experiences/issues/84
