### ISSUE TITLE
Marketing Website - Shielded Pool Page

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-experiences#68]
## Overview

This is part of the Epic #56 for the completion of the Shielded Pool Protocol page. 

### Content

Content for landing page can be found on Notion [here](https://www.notion.so/hicommonwealth/Shielded-Pool-Page-db64a52a1d76472d8908d49fa4bd4b51). 

### Task Checklist 

- [ ] use cases section
- [ ] merkle tree illustration
- [ ] extensions section
- [ ] Security section (needs a second look on the [content side](https://www.notion.so/hicommonwealth/Shielded-Pool-Page-db64a52a1d76472d8908d49fa4bd4b51))
- [ ] developer ctas forming the bottom content section
- [ ] stylistic edits

### Dev Handoff Links

- TBD
