### ISSUE TITLE
[TASK] Webbsite Brand Kit

### ISSUE THREAD

**Issue by seeddisperser** [webb-tools/webb-experiences#80]
## Overview

Create a page to host the brand assets for easy access. Need for desktop and mobile.

### Examples

- https://v1.cosmos.network/presskit
- https://polkadot.network/ecosystem/brand-hub/

**Comment by monaiuu** [comment]
### Tasks:
- [x] Create desktop brand kit page
- [x] Create mobile brand kit page
- [x] Organize all required assets 
- [x] Add brand kit navigation link from webbsite / footer

**Comment by monaiuu** [comment]
## Webb Brand Kit Handoff

Please see below for the requirements for Webb's Brand Kit. 

![Image](https://user-images.githubusercontent.com/109539270/233758986-627cbce4-9d77-4cb8-95df-b009ff343d07.png)

- [ ] Implement Webb Brand Kit in desktop view
- [ ] Implement Webb Brand Kit in mobile view
- [ ] Gather all assets appropriately to be downloaded
- [ ] Add link to footer component for `Brand Kit` below Resources section

Figma Link:
https://www.figma.com/file/d5T0P9k4anUGdBlqgh4ueW/%F0%9F%96%A5%EF%B8%8F-Webb-Website?node-id=2391%3A83280&t=efsptjtm5FlBowH5-1
